compilemsg:
	@echo "[!] Compiling : Analysis of Algorithms"
	@echo
	bash ./compile.sh

collegestuffs: compilemsg $(OUTPUT)
	@echo
	@echo "[!] Analysis of Algorithms : Successful"
	@echo

clean:
	@echo "#####################################"
	@echo "# Cleaning : Analysis of Algorithms #"
	@echo "#####################################"
	find . -name *.o -exec rm -f {} \;
	@echo "[!] Done"
	@echo
