compilemsg:
	@echo "[!] Compiling : Object Oriented Programming Methodologies"
	@echo
	bash ./compile.sh

collegestuffs: compilemsg $(OUTPUT)
	@echo
	@echo "[!] Object Oriented Programming Methodologies : Successful"
	@echo

clean:
	@echo "########################################################"
	@echo "# Cleaning : Object Oriented Programming Methodologies #"
	@echo "########################################################"
	$(RM) *.class
	@echo "[!] Done"
	@echo
