compilemsg:
	@echo "[!] Compiling : Structured Programming Approach"
	@echo
	bash ./compile.sh

collegestuffs: compilemsg $(OUTPUT)
	@echo
	@echo "[!] Structured Programming Approach : Successful"
	@echo

clean:
	@echo "##############################################"
	@echo "# Cleaning : Structured Programming Approach #"
	@echo "##############################################"
	find . -name *.o -exec rm -f {} \;
	@echo "[!] Done"
	@echo
