compilemsg:
	@echo "[!] Compiling : Data Structures"
	@echo
	bash ./compile.sh

collegestuffs: compilemsg $(OUTPUT)
	@echo
	@echo "[!] Data Structures : Successful"
	@echo

clean:
	@echo "##############################"
	@echo "# Cleaning : Data Structures #"
	@echo "##############################"
	find . -name *.o -exec rm -f {} \;
	@echo "[!] Done"
	@echo
